#!/bin/bash
# Test script for Nodo CLI
# Tests various use cases and verifies output

set -e  # Exit on error

CLI="./build/Debug/nodo_cli/nodo_cli"
TEST_DIR="/tmp/nodo_cli_tests"

echo "========================================"
echo "Nodo CLI Test Suite"
echo "========================================"
echo

# Setup
mkdir -p "$TEST_DIR"
cd "$(dirname "$0")/.."

# Test 1: Help message
echo "Test 1: Help message"
echo "--------------------"
$CLI --help
echo "✓ Help displayed successfully"
echo

# Test 2: Simple graph execution
echo "Test 2: Simple graph (Simple_A.nfg)"
echo "-----------------------------------"
$CLI projects/Simple_A.nfg "$TEST_DIR/simple_output.obj" --stats
if [ -f "$TEST_DIR/simple_output.obj" ]; then
    SIZE=$(wc -c < "$TEST_DIR/simple_output.obj")
    echo "✓ Output file created ($SIZE bytes)"
else
    echo "✗ Output file not created"
    exit 1
fi
echo

# Test 3: Complex graph with verbose mode
echo "Test 3: Complex graph with verbose (copy_to_points.nfg)"
echo "-------------------------------------------------------"
$CLI projects/copy_to_points.nfg "$TEST_DIR/copy_to_points.obj" --verbose --stats
if [ -f "$TEST_DIR/copy_to_points.obj" ]; then
    SIZE=$(wc -c < "$TEST_DIR/copy_to_points.obj")
    LINES=$(wc -l < "$TEST_DIR/copy_to_points.obj")
    echo "✓ Output file created ($SIZE bytes, $LINES lines)"
else
    echo "✗ Output file not created"
    exit 1
fi
echo

# Test 4: Verify OBJ format
echo "Test 4: Verify OBJ format"
echo "-------------------------"
HEAD=$(head -5 "$TEST_DIR/simple_output.obj")
if echo "$HEAD" | grep -q "# OBJ file generated by Nodo"; then
    echo "✓ OBJ header found"
else
    echo "✗ Invalid OBJ header"
    exit 1
fi

if echo "$HEAD" | grep -q "^v "; then
    echo "✓ Vertex data found"
else
    echo "✗ No vertex data"
    exit 1
fi
echo

# Test 5: Error handling - missing file
echo "Test 5: Error handling (missing file)"
echo "-------------------------------------"
if $CLI nonexistent.nfg "$TEST_DIR/error.obj" 2>&1 | grep -q "Error"; then
    echo "✓ Error message displayed correctly"
else
    echo "✗ No error for missing file"
    exit 1
fi
echo

# Test 6: Boolean operations
echo "Test 6: Boolean subtract (boolean_subtract_spheres.nfg)"
echo "-------------------------------------------------------"
if [ -f "projects/boolean_subtract_spheres.nfg" ]; then
    $CLI projects/boolean_subtract_spheres.nfg "$TEST_DIR/boolean.obj" --stats
    if [ -f "$TEST_DIR/boolean.obj" ]; then
        echo "✓ Boolean operation executed"
    else
        echo "✗ Boolean output not created"
        exit 1
    fi
else
    echo "⊘ Boolean test graph not found (skipped)"
fi
echo

# Summary
echo "========================================"
echo "All tests passed! ✓"
echo "========================================"
echo
echo "Generated files in: $TEST_DIR"
ls -lh "$TEST_DIR"/*.obj
echo

# Cleanup option
read -p "Delete test files? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    rm -rf "$TEST_DIR"
    echo "✓ Test files deleted"
fi
